Migration to firestore
slosa-smartare/backend pull request #46
Opened 2020-11-26 08:33 UTC by PriscilaAlfaro

2020-12-02 17:30 UTC, wirob requested changes

2020-12-03 10:14 UTC, PriscilaAlfaro commented on src/controllers/answers.js
> +    const totalVotes = answers.length;
getAllAnswersForAProduct return an array with all the answers for a specific product. This is used to populate the charts.

2020-12-03 10:14 UTC, PriscilaAlfaro commented on src/controllers/answers.js
>        const receivMessage = answer.receiverMessage;
Understood.

2020-12-03 10:15 UTC, PriscilaAlfaro commented on src/controllers/products.js
>      return res.status(500).send();
Understood.

2020-12-04 19:18 UTC, kosmolet approved these changes

2020-12-07 09:49 UTC, wirob requested changes

2020-12-07 09:49 UTC, wirob commented on src/controllers/questions.js
>      return res.status(500).send();
Missing the error to be sent to the client here.

2020-12-07 09:51 UTC, wirob requested changes

2020-12-07 09:51 UTC, wirob commented on src/controllers/questions.js
>      return res.status(500).send();
```suggestion
    return res.status(500).send(err);
```

2020-12-07 10:35 UTC, PriscilaAlfaro commented on src/controllers/questions.js
>      return res.status(500).send();
Understood 🙂

2020-12-07 11:42 UTC, wirob submitted a review, later dismissed
Great job! I love it that you found the time to make some tests too! 🎊 🎉

2020-12-07 12:47 UTC, kosmolet approved these changes

2020-12-07 16:25 UTC, kosmolet submitted a review, later dismissed

2020-12-07 16:40 UTC, GayathriVaradan approved these changes

2020-12-07 17:04 UTC, zohresalimi approved these changes

2020-12-07 17:05 UTC, kosmolet approved these changes

2020-12-07 17:05 UTC, meerajm approved these changes

2020-12-07 17:05 UTC, merged